apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels: # etcd -- key: value 
    x1: helloashu
  name: ashuwebapp # name of pod 
spec:
  containers:
  - image: dockerashu/ashuhttpd:v1 # docker image from docker hub 
    name: ashuwebapp # name of container 
    ports: # app port 
    - containerPort: 80
    resources: {}
    imagePullPolicy: Always 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels: # ignore label of service 
    app: ashusvc1
  name: ashusvc1 # name of service 
spec:
  ports:
  - name: httpreq
    port: 1234 # service port number which will be binded with service IP 
    protocol: TCP
    targetPort: 80 # app port which is running inside POD 
    nodePort: 32174
  selector: # Pod FINDER using label of pod 
   x1: helloashu
  type: NodePort # type of service 
status:
  loadBalancer: {}

